import type { HookContext } from "@w6w/types";

/**
 * Process Street Public API v1.1 — verified against the vendor's own OpenAPI 3.1 document at
 * `public-api.process.st/api/v1.1/docs/docs.yaml` (2.3MB, fetched directly) on 2026-09-06, plus
 * live probes against the base URL below.
 *
 * **Base URL is `public-api.process.st/api/v1.1`** — the spec's `servers[0].url`. Note some
 * `Link.href` *examples* inside the spec show `api.process.st` (no `public-` prefix) instead;
 * that host does not resolve for this API and is a documentation artifact, not a real host — this
 * app only ever builds URLs from `API_URL` and never trusts a `links[]` `href` verbatim as a host.
 *
 * ## Auth
 *
 * `X-API-Key: <key>` (the `apiKeyAuth` security scheme). A second, beta `httpAuth` bearer scheme
 * is also declared in the spec but undocumented beyond "Bearer token (beta)" — not implemented
 * here.
 *
 * ## Pagination
 *
 * Opaque cursor named `_` (the spec's own description: "yes, just an underscore"). Every list
 * response body carries a `links[]` array (HATEOAS, RFC 5988 relation names); when more pages
 * exist there's an entry with `name: "next"` whose `href` is a fully-formed URL. This app never
 * fetches that URL directly (its host is not guaranteed to be `network.allow`-safe — see above);
 * instead `nextCursor` below pulls just the `_` query value back out of it, so callers pass that
 * value into the next call's own `cursor` param, exactly like the spec's own fallback path
 * ("You can also reuse the `_` value from one response by passing it as the `_` query parameter").
 *
 * **Not every list endpoint is actually paginated this way.** `GET /workflow-runs` ("Search
 * workflow runs") is capped at "the latest 200 workflow runs of a workflow" with NO `_` parameter
 * and no `links[]` cursor at all — it is a different, older operation from the real cursor-paginated
 * `GET /workflow-runs/list` ("List all workflow runs"). This app exposes both
 * (`workflow-run-search` / `workflow-run-list`) under clearly different names rather than picking
 * one, because `workflow-run-search` is the only one of the two that can filter by `name` or
 * collected form-field values.
 *
 * ## Errors
 *
 * `{"error": string, "errorCode"?: string, "requestId"?: string, "details"?: object}`
 * (`ErrorInfo`). The spec states `errorCode`/`requestId` are populated "on responses generated by
 * the public API exception handler, which covers the great majority of errors" but that some
 * low-level failures fall back to a bare `{"error": "..."}`. **Verified live 2026-09-06: a missing
 * OR invalid `X-API-Key` is exactly that low-level case** — `GET /testAuth` with no key answers
 * `401 {"error":"Unauthorized"}`, and with a garbage key `401 {"error":"Unable to verify
 * credentials."}` — neither carries `errorCode`. Any code branching on `errorCode` for the most
 * common failure (a bad credential) will find it absent; `errorMessage` below always falls back to
 * the raw `error` string plus the HTTP status, exactly as the spec's own prose recommends.
 *
 * ## Idempotency (as documented, with one gap)
 *
 * `GET` is always safe to retry; `PUT` and `DELETE` are documented idempotent. `POST` is
 * documented as "generally not safe to blindly retry" *except* that "attach a `referenceId` on
 * create — calling `createWorkflowRun` twice with the same `referenceId` will return the existing
 * run instead of creating a duplicate." **Verified against the spec's own schema: this is not
 * true today.** `CreateWorkflowRunRequest` has exactly four properties —
 * `workflowId`/`name`/`dueDate`/`shared` — no `referenceId` field exists anywhere on it. Sending
 * one is therefore a silently-ignored extra field, not a dedupe key. `workflow-run-create` is
 * marked `idempotent: false` accordingly, and this app does not pretend the field works.
 *
 * ## Rate limits (largely undocumented)
 *
 * The spec's prose only says: on a 429, "wait for the duration specified in the `Retry-After`
 * header." **Verified live 2026-09-06 (an unauthenticated and a garbage-key `GET /testAuth`):**
 * every response — including a 401 — actually carries FOUR undocumented headers not mentioned
 * anywhere in the OpenAPI document: `X-Ip-Rate-Limit-{Limit,Remaining,Reset}` (keyed by caller IP)
 * and `X-Api-Key-Rate-Limit-{Limit,Remaining,Reset}` (keyed by the literal key string sent — a
 * garbage key still gets its own fresh 2500-request bucket). `Retry-After` was also observed live
 * as an HTTP-date (`Sun, 06 Sep 2026 20:04:44 GMT`), not the delta-seconds format `Retry-After` is
 * most commonly assumed to carry. `health/quota.ts` reads the `X-Api-Key-Rate-Limit-*` trio.
 */
export const API_URL = "https://public-api.process.st/api/v1.1";

export interface PsLink {
  name: string;
  href: string;
  rel?: string;
  type?: "Api" | "App";
}

export interface PsErrorInfo {
  error?: string;
  errorCode?: string;
  requestId?: string;
  details?: Record<string, string>;
}

/**
 * Normalise Process Street's `ErrorInfo` body to one readable string. Falls back to the raw text
 * when it isn't JSON — an undocumented response shape is never silently swallowed as "undefined".
 * `errorCode` is appended when present, but per `client.ts`'s own doc comment it is ABSENT on the
 * most common failure (a bad/missing API key), so callers must not assume it.
 */
export function errorMessage(text: string): string {
  if (!text) return "";
  try {
    const body = JSON.parse(text) as PsErrorInfo;
    if (!body.error) return text;
    const suffix = body.errorCode ? ` (${body.errorCode})` : "";
    return `${body.error}${suffix}`;
  } catch {
    return text;
  }
}

/** Parse the `ErrorInfo` body without collapsing it to a string, for callers that branch on `errorCode`. */
export function parseError(text: string): PsErrorInfo | undefined {
  if (!text) return undefined;
  try {
    return JSON.parse(text) as PsErrorInfo;
  } catch {
    return undefined;
  }
}

/**
 * Pull the `_` cursor value back out of the `links[]` entry named `"next"`. Returns `undefined`
 * when there is no next page (either `links` is absent, or has no `"next"` entry) — the spec
 * states plainly that's the only end-of-list signal, there is no total-count field.
 */
export function nextCursor(links: PsLink[] | undefined): string | undefined {
  const next = links?.find((l) => l.name === "next");
  if (!next) return undefined;
  try {
    return new URL(next.href).searchParams.get("_") ?? undefined;
  } catch {
    return undefined;
  }
}

/** Drop keys the caller left `undefined` so a PUT/POST body never carries a stray `undefined`. */
export function compact<T extends Record<string, unknown>>(obj: T): Partial<T> {
  const out: Partial<T> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v !== undefined) (out as Record<string, unknown>)[k] = v;
  }
  return out;
}

export interface RequestOptions {
  method?: string;
  query?: Record<string, string | number | boolean | undefined | null>;
  body?: Record<string, unknown>;
}

export interface PsResult<T> {
  data: T;
  status: number;
  headers: Headers;
}

/**
 * Thin wrapper over `ctx.fetch`. Never sets `X-API-Key` — the runtime routes every request
 * through the auth `sign` hook, which is the only code handed the credential.
 */
export class ProcessStreetClient {
  constructor(private ctx: HookContext) {}

  async request<T = unknown>(
    path: string,
    options: RequestOptions = {},
  ): Promise<PsResult<T>> {
    const url = new URL(`${API_URL}${path}`);
    for (const [k, v] of Object.entries(options.query ?? {})) {
      if (v === undefined || v === null || v === "") continue;
      url.searchParams.set(k, String(v));
    }

    const headers: Record<string, string> = { accept: "application/json" };
    const init: RequestInit = { method: options.method ?? "GET", headers };
    if (options.body !== undefined) {
      headers["content-type"] = "application/json";
      init.body = JSON.stringify(options.body);
    }

    const res = await this.ctx.fetch(url.toString(), init);
    const text = await res.text();
    if (!res.ok) {
      const detail = errorMessage(text);
      throw new Error(
        `Process Street ${res.status} ${res.statusText} for ${init.method} ${url.pathname}` +
          (detail ? `: ${detail}` : ""),
      );
    }
    const data = text ? (JSON.parse(text) as T) : (undefined as T);
    return { data, status: res.status, headers: res.headers };
  }
}
