import type { AuthDefinition } from "@w6w/types";
import { API_BASE, API_PREFIX } from "../lib/client.ts";

/**
 * CompanyCam access token — `Authorization: Bearer <token>`.
 *
 * Verified against the vendor's Getting Started guide
 * (`docs.companycam.com/docs/getting-started`, fetched 2026-08-11), the
 * `BearerAuth` security scheme in CompanyCam's OpenAPI document, and live
 * probes against `api.companycam.com` on the same day.
 *
 * A token is generated by the account holder at
 * `app.companycam.com/access_tokens`; the vendor's guidance is that this is the
 * right credential for an integration into your own account, and OAuth (see
 * `auth/oauth2.ts`) for an integration published to other companies. Both
 * present the same `Authorization: Bearer` header on the same endpoints.
 *
 * The token carries the whole account: CompanyCam's API has no scopes for
 * access tokens (the `read`/`write`/`destroy` scopes exist only in the OAuth
 * flow), so a connection made this way can do everything this app can do,
 * including deleting projects. That is the vendor's design, not a choice made
 * here, and it is why the destructive actions carry the warnings they do.
 */

export interface CompanyCamCredential {
  accessToken: string;
}

/**
 * The one place the wire format is built. Exported so `test` and `afterConnect`
 * exercise the same code path `sign` does — a hand-rolled second copy is how a
 * probe ends up sending a header the real requests do not.
 */
export function authHeaders(credential: Partial<CompanyCamCredential>): Record<string, string> {
  return { authorization: `Bearer ${credential.accessToken ?? ""}` };
}

/**
 * The credential-liveness probe.
 *
 * `GET /v2/users/current` was chosen by reading the response schema and by
 * measuring the wire on 2026-08-11, not by its name:
 *
 * **(a) It requires a credential.** Unauthenticated it answers
 * `401 {"errors":["Unauthorized"]}` with `content-type: application/json`;
 * so does a syntactically plausible but fake bearer token. Both were observed
 * live. Every endpoint in this API behaves the same way — there is no public
 * endpoint under `/v2` that a credential-less connection could sail through,
 * which is the trap that ruled out `/v2/store` for Apify and `/v1/voices` for
 * ElevenLabs.
 *
 * **(b) It needs no scope.** An OAuth token granted only `read` reaches it, and
 * a probe that needed `write` would report a correctly-scoped read-only
 * connection as broken. The obvious alternatives are collection reads
 * (`/v2/projects`, `/v2/webhooks`) which cost the vendor real work and, for
 * `/v2/webhooks`, return a secret — see (c).
 *
 * **(c) It returns no credential material.** The `User` schema is id, company
 * id, name, email address, phone number, profile image URLs and timestamps.
 * Compare `GET /v2/webhooks`, whose every row carries `token`, the HMAC key
 * CompanyCam signs webhook deliveries with — that endpoint can never be a probe
 * for the same reason Mailjet's `/apikey` and Follow Up Boss's `/me` are banned
 * pack-wide.
 *
 * The email address in the response is the account holder's own, already known
 * to whoever pasted the token, and it is what makes a list of connections
 * readable. It is used for `connectionLabel` and nothing else.
 */
export const PROBE_PATH = "/users/current";

/**
 * Why a webhook read is not the probe — kept as an exported constant so the
 * reason survives the next person who notices `/v2/webhooks` also needs a
 * credential.
 */
export const WHY_NOT_WEBHOOKS =
  "GET /v2/webhooks returns Webhook.token, the HMAC key CompanyCam signs deliveries with";

/**
 * Classify a failed probe from the response BODY, never from the status alone.
 *
 * There is not much body to classify with — `{"errors":["Unauthorized"]}` is
 * all a 401 carries, and it is byte-identical for a missing credential and a
 * revoked one (measured 2026-08-11 with no header, and with
 * `Authorization: Bearer deadbeef…`). So this reports both possibilities rather
 * than asserting one. A `302`/HTML answer is a third case entirely: it means
 * the request never reached the v2 API.
 */
export function explainProbeFailure(status: number, contentType: string, body: string): string {
  if (contentType && !/\bjson\b/i.test(contentType)) {
    return `CompanyCam answered ${status} with a non-JSON body — the request did not reach the ` +
      "v2 API (an unknown path redirects to the web sign-in page).";
  }
  let messages: string[] = [];
  try {
    const parsed = JSON.parse(body) as { errors?: unknown };
    if (Array.isArray(parsed?.errors)) messages = parsed.errors.map((e) => String(e));
  } catch { /* not JSON — the status is all there is */ }
  const detail = messages.length > 0 ? `: ${messages.join("; ")}` : "";

  if (status === 401) {
    return `CompanyCam rejected the credential (401${detail}). This API answers the same 401 ` +
      "whether no token arrived or the token is wrong, so check both: that the token was " +
      "copied exactly from app.companycam.com/access_tokens, and that it has not been " +
      "revoked there.";
  }
  if (status === 403) {
    return `CompanyCam refused the request (403${detail}). The token is recognised but this ` +
      "account is not permitted to read its own user — check the plan, since API access " +
      "requires Pro, Premium or Elite.";
  }
  return `CompanyCam returned HTTP ${status} for ${PROBE_PATH}${detail}`;
}

const accessToken: AuthDefinition = {
  key: "access-token",
  type: "bearer",
  displayName: "Access Token",
  description:
    "Paste an access token generated at app.companycam.com/access_tokens. It carries the whole " +
    "account — CompanyCam applies no scopes to access tokens — so prefer OAuth for an " +
    "integration used by other companies.",
  connectionLabel: "CompanyCam ({{user.email}})",
  fields: [
    {
      key: "accessToken",
      label: "Access Token",
      type: "secret",
      required: true,
      hint: "app.companycam.com/access_tokens. API access requires a Pro, Premium or Elite plan.",
    },
  ],

  /**
   * The only hook handed the raw credential, and it runs network-less: it
   * stamps the bearer header and returns. CompanyCam documents no query-string
   * form of the token, and this app would not use one if it did.
   */
  sign({ request, credential }) {
    const cred = credential as Partial<CompanyCamCredential>;
    for (const [name, value] of Object.entries(authHeaders(cred))) {
      request.headers[name] = value;
    }
    return request;
  },

  /** See {@link PROBE_PATH} for why this endpoint and not a collection read. */
  async test({ credential }, ctx) {
    const cred = credential as Partial<CompanyCamCredential>;
    const token = (cred?.accessToken ?? "").trim();
    if (!token) return { ok: false, message: "credential missing accessToken" };

    const res = await ctx.fetch(`${API_BASE}${API_PREFIX}${PROBE_PATH}`, {
      headers: { accept: "application/json", ...authHeaders({ accessToken: token }) },
    });
    if (res.ok) return { ok: true };

    const contentType = res.headers.get("content-type") ?? "";
    const body = await res.text().catch(() => "");
    return { ok: false, message: explainProbeFailure(res.status, contentType, body) };
  },

  /**
   * Publish the connected user's email and name, and nothing else.
   *
   * A list of connections that all read "CompanyCam" is unusable, and this is
   * the one company-wide credential shape where the account holder is the only
   * distinguishing fact. The response also carries a phone number and profile
   * image URLs; they are dropped on the floor rather than published, because a
   * connection label needs neither.
   *
   * A failure here is deliberately silent: `test` has already established the
   * token is live, and a missing display label must not fail a good connection.
   */
  async afterConnect({ credential }, ctx) {
    const cred = credential as Partial<CompanyCamCredential>;
    try {
      const res = await ctx.fetch(`${API_BASE}${API_PREFIX}${PROBE_PATH}`, {
        headers: { accept: "application/json", ...authHeaders(cred) },
      });
      if (!res.ok) return {};
      const user = await res.json() as {
        id?: string;
        email_address?: string;
        first_name?: string;
        last_name?: string;
        company_id?: string;
      };
      const email = user?.email_address;
      if (!email) return {};
      const name = [user.first_name, user.last_name].filter(Boolean).join(" ");
      return {
        user: { id: user.id, email, name: name || undefined, companyId: user.company_id },
      };
    } catch {
      return {};
    }
  },
};

export default accessToken;
