/**
 * Yelp Leads — read and respond to Leads generated by Yelp users on the
 * businesses a reseller partner has subscribed to for webhook notifications.
 *
 * Every path, method, parameter and response shape in this app was read off
 * Yelp's own OpenAPI 3.1 document, embedded server-side in each Leads
 * reference page at `docs.developer.yelp.com` (each page's own
 * `oasDefinition`, not a third-party integration directory), and
 * cross-checked against that page's rendered "server URL"
 * (`data-testid="serverurl"`) — fetched and diffed 2026-09-06 for all seven
 * Leads endpoints plus the OAuth token/revoke endpoints. See `lib/client.ts`
 * and `auth/oauth2.ts` for the endpoint-by-endpoint detail.
 *
 * ## Access to this API is restricted
 *
 * "Access to the Leads API is currently limited to Yelp advertising and
 * listing management reseller partners. Participation in these partnerships
 * is subject to a minimum spend requirement" — Yelp's own words on
 * `docs.developer.yelp.com/docs/leads-api`. Yelp's stated recommendation for
 * everyone else is its no-code Zapier integration, which this app does not
 * attempt to replace.
 *
 * ## Scoped tightly to what the API documents
 *
 * Seven actions, matching the seven operations in the Leads OpenAPI
 * document's `paths` — nothing padded in. A "Message the business" business
 * (one lacking that Yelp profile feature) is explicitly ineligible for the
 * Leads API per Yelp's own overview, which this app cannot detect or enforce
 * — Yelp itself returns a 403 for a business that does not qualify.
 */
import type { AppDefinition } from "@w6w/types";
import oauth2 from "./auth/oauth2.ts";

import getLead from "./actions/get-lead.ts";
import getLeadEvents from "./actions/get-lead-events.ts";
import writeLeadEvent from "./actions/write-lead-event.ts";
import markLeadAsReplied from "./actions/mark-lead-as-replied.ts";
import markLeadEventAsRead from "./actions/mark-lead-event-as-read.ts";
import getLeadIdsForBusiness from "./actions/get-lead-ids-for-business.ts";
import getLeadMetrics from "./actions/get-lead-metrics.ts";

import service from "./health/service.ts";
import quota from "./health/quota.ts";

export default {
  actions: [
    getLead,
    getLeadEvents,
    writeLeadEvent,
    markLeadAsReplied,
    markLeadEventAsRead,
    getLeadIdsForBusiness,
    getLeadMetrics,
  ],
  auth: [oauth2],
  healthChecks: [service, quota],
} satisfies AppDefinition;
