import type { OutputField } from "@w6w/types";

/**
 * Allowed `lead_type` values, verified against `whatconverts.com/api/leads/` (both the
 * list-filter parameter and the create-lead parameter document this exact set). This is
 * WhatConverts's own umbrella for every conversion event it tracks — a phone call, a web
 * form submission, a chat, an email, an appointment, a transaction, a text message, a
 * calendar/pixel "event", or "other" — surfaced through one `leads` resource rather than
 * a resource per channel.
 */
export const LEAD_TYPES = [
  "appointment",
  "chat",
  "email",
  "event",
  "other",
  "phone_call",
  "text_message",
  "transaction",
  "web_form",
] as const;

/** `whatconverts.com/api/leads/` — the "get all leads" / "get single lead" response shape. */
export const LEAD_OUTPUT_FIELDS: OutputField[] = [
  { key: "account_id", type: "number", label: "Account ID" },
  { key: "profile_id", type: "number", label: "Profile ID" },
  { key: "profile", type: "string", label: "Profile name" },
  { key: "lead_id", type: "number", label: "Lead ID" },
  { key: "user_id", type: "string", label: "WhatConverts user ID (visitor identity)" },
  { key: "lead_type", type: "string", label: "Lead type" },
  { key: "lead_status", type: "string", label: "Lead status — Repeat or Unique" },
  { key: "date_created", type: "string", label: "Date created (ISO 8601, UTC)" },
  { key: "quotable", type: "string", label: "Quotable — Yes, No, Pending or Not Set" },
  { key: "quote_value", type: "number", label: "Quote value" },
  { key: "sales_value", type: "number", label: "Sales value" },
  { key: "spotted_keywords", type: "string", label: "Spotted keywords" },
  { key: "lead_score", type: "number", label: "Lead score" },
  { key: "lead_state", type: "string", label: "Lead state" },
  { key: "spam", type: "boolean", label: "Marked as spam" },
  { key: "duplicate", type: "boolean", label: "Marked as duplicate" },
  { key: "lead_source", type: "string", label: "Traffic source" },
  { key: "lead_medium", type: "string", label: "Traffic medium" },
  { key: "lead_campaign", type: "string", label: "Campaign" },
  { key: "lead_content", type: "string", label: "Content" },
  { key: "lead_keyword", type: "string", label: "Keyword" },
  { key: "ip_address", type: "string", label: "Visitor IP address" },
  { key: "notes", type: "string", label: "Notes" },
  { key: "contact_name", type: "string", label: "Contact name" },
  { key: "contact_company_name", type: "string", label: "Contact company name" },
  { key: "contact_email_address", type: "string", label: "Contact email address" },
  { key: "contact_phone_number", type: "string", label: "Contact phone number" },
  { key: "email_address", type: "string", label: "Email address" },
  { key: "phone_number", type: "string", label: "Phone number" },
  { key: "gclid", type: "string", label: "Google click identifier" },
  { key: "msclkid", type: "string", label: "Microsoft click identifier" },
  { key: "unbounce_page_id", type: "string", label: "Unbounce page ID" },
  { key: "unbounce_variant_id", type: "string", label: "Unbounce variant ID" },
  { key: "unbounce_visitor_id", type: "string", label: "Unbounce visitor ID" },
  { key: "salesforce_user_id", type: "string", label: "Salesforce user ID" },
  { key: "roistat_visit_id", type: "string", label: "Roistat visit ID" },
  { key: "hubspot_visitor_id", type: "string", label: "HubSpot visitor ID" },
  { key: "facebook_browser_id", type: "string", label: "Facebook browser ID" },
  { key: "facebook_visitor_id", type: "string", label: "Facebook visitor ID" },
  { key: "vwo_account_id", type: "string", label: "VWO account ID" },
  { key: "vwo_experiment_id", type: "string", label: "VWO experiment ID" },
  { key: "vwo_variant_id", type: "string", label: "VWO variant ID" },
  { key: "vwo_user_id", type: "string", label: "VWO user ID" },
  { key: "google_analytics_client_id", type: "string", label: "Google Analytics client ID" },
  { key: "lead_url", type: "string", label: "URL where the lead took place" },
  { key: "landing_url", type: "string", label: "URL where the visitor first arrived" },
  { key: "operating_system", type: "string", label: "Operating system" },
  { key: "browser", type: "string", label: "Browser" },
  { key: "device_type", type: "string", label: "Device type" },
  { key: "device_make", type: "string", label: "Device make" },
  {
    key: "phone_name",
    type: "string",
    label: "Tracking number name (phone_call, text_message)",
  },
  {
    key: "tracking_number",
    type: "string",
    label: "E.164 tracking number (phone_call, text_message)",
  },
  {
    key: "destination_number",
    type: "string",
    label: "E.164 destination number (phone_call)",
  },
  {
    key: "caller_number",
    type: "string",
    label: "E.164 caller number (phone_call, text_message)",
  },
  { key: "caller_name", type: "string", label: "Caller name (phone_call)" },
  { key: "call_duration", type: "string", label: "Formatted call duration (phone_call)" },
  { key: "call_duration_seconds", type: "number", label: "Call duration in seconds (phone_call)" },
  { key: "city", type: "string", label: "City" },
  { key: "state", type: "string", label: "State" },
  { key: "zip", type: "string", label: "ZIP / postal code" },
  { key: "country", type: "string", label: "Country" },
  {
    key: "answer_status",
    type: "string",
    label: "Answered, No Answer, or Busy (phone_call)",
  },
  { key: "call_status", type: "string", label: "In Progress or Completed (phone_call)" },
  {
    key: "line_type",
    type: "string",
    label: "Caller line type (phone_call, text_message)",
  },
  { key: "recording", type: "string", label: "Call recording download URL (phone_call)" },
  { key: "play_recording", type: "string", label: "Call recording play URL (phone_call)" },
  { key: "voicemail", type: "string", label: "Voicemail download URL (phone_call)" },
  { key: "play_voicemail", type: "string", label: "Voicemail play URL (phone_call)" },
  { key: "call_transcription", type: "string", label: "Call transcription (phone_call)" },
  {
    key: "voicemail_transcription",
    type: "string",
    label: "Voicemail transcription (phone_call)",
  },
  { key: "message", type: "string", label: "Message text (text_message)" },
  { key: "chat_status", type: "string", label: "In Progress or Completed (chat)" },
  { key: "event_category", type: "string", label: "Event category (event)" },
  { key: "event_action", type: "string", label: "Event action (event)" },
  { key: "event_label", type: "string", label: "Event label (event)" },
  { key: "transaction_id", type: "string", label: "Transaction ID (transaction)" },
  { key: "transaction_tax", type: "number", label: "Transaction tax (transaction)" },
  { key: "transaction_shipping", type: "number", label: "Transaction shipping (transaction)" },
  { key: "sender_name", type: "string", label: "Sender name (email)" },
  { key: "email_subject", type: "string", label: "Email subject (email)" },
  { key: "email_message", type: "string", label: "Email message (email)" },
  { key: "lead_analysis", type: "object", label: "AI lead analysis (Elite plans)" },
  { key: "last_updated", type: "string", label: "Date last updated (ISO 8601, UTC)" },
  { key: "additional_fields", type: "object", label: "Additional fields" },
  {
    key: "field_mappings",
    type: "object",
    label: "Field mappings (Profile Key or profile_id only)",
  },
  {
    key: "custom_fields",
    type: "object",
    label: "Custom fields (Profile Key or profile_id only)",
  },
  {
    key: "customer_journey",
    type: "array",
    label: "Customer journey (Elite plans; only when requested)",
  },
];
