import type { ActionDefinition } from "@w6w/types";
import { RechargeClient } from "../lib/client.ts";

/**
 * `GET /token_information` — details about the connected token itself. No
 * scope is documented for this endpoint — it describes the token's own
 * label and origin, not a scoped resource.
 *
 * Response envelope: `{"token_information": {"client": {"name",
 * "contact_email"}, "contact_email", "name", "scopes"}}`. `client` is
 * populated only when the token was generated by an OAuth app, per the
 * reference; for a merchant-created ("private app") token, `name` carries
 * the label prefixed `[Private App]`.
 *
 * This is also the endpoint `auth/api-token.ts` uses as its liveness probe
 * and `health/quota.ts` reads its rate-limit header from — see both for why.
 */
const tokenInformationGet: ActionDefinition<Record<string, never>> = {
  key: "token-information-get",
  type: "read",
  resource: "token-information",
  title: "Get Token Information",
  description: "Return the connected API token's own name, scopes, and (for an OAuth-app " +
    "token) the client that generated it.",
  params: [],
  output: [
    { key: "name", type: "string", label: "Token name" },
    { key: "contact_email", type: "string", label: "Contact email" },
    { key: "scopes", type: "array", label: "Granted scopes" },
    { key: "client", type: "object", label: "OAuth client info (if applicable)" },
  ],

  async execute(_input, ctx) {
    const client = new RechargeClient(ctx);
    return await client.single("/token_information", "token_information");
  },
};

export default tokenInformationGet;
