import type { AuthDefinition } from "@w6w/types";
import { API_BASE, formatFeedlyError } from "../lib/client.ts";

/**
 * Feedly Enterprise API token — `Authorization: Bearer <token>`.
 *
 * Verified against the Authorization reference page (fetched 2026-09-06):
 * "Self service API tokens are only available to Enterprise clients... Access
 * tokens can be passed in the 'Authorization' request header like regular
 * access tokens", with the example
 * `curl -H 'Authorization: Bearer YourAccessToken' https://cloud.feedly.com/v3/profile`.
 * There is no OAuth2 authorization-code flow documented anywhere in the
 * current reference — this token is minted once, by an admin, from
 * `https://feedly.com/i/team/api`, and used forever until revoked.
 *
 * ## The probe: `GET /v3/profile`
 *
 * `/v3/profile` is not in the current reference's endpoint list — it appears
 * only as the Authorization page's own worked curl example — but it is real:
 * a live unauthenticated probe on 2026-09-06 answered
 * `401 {"errorCode":401,"errorMessage":"must provide authorization token"}`,
 * and a syntactically-plausible fake token answered
 * `401 {"errorCode":401,"errorMessage":"invalid token"}`. Both are
 * structured, stable error codes, not a guess from a bare status.
 *
 * It is preferred over every documented alternative because it needs no
 * enterprise-admin privilege and touches no team data — `GET
 * /v3/enterprise/users` and `GET /v3/enterprise/collections` both require the
 * caller to be a team admin (403 "Insufficient permissions" is documented for
 * both), which would report a perfectly good non-admin Enterprise token as a
 * broken Connection.
 *
 * This app does not model `/v3/profile`'s success response as an Action: the
 * current reference documents no schema for it at all (it is absent from the
 * endpoint list), so guessing field names for the profile is exactly the kind
 * of unverified detail this app leaves out. `test` only needs `res.ok`.
 */

export interface FeedlyCredential {
  apiToken: string;
}

export const PROBE_PATH = "/v3/profile";

export function authHeaders(credential: Partial<FeedlyCredential>): Record<string, string> {
  return { authorization: `Bearer ${credential.apiToken ?? ""}` };
}

const bearerToken: AuthDefinition = {
  key: "bearer-token",
  type: "bearer",
  displayName: "API Token",
  description:
    "Paste an Enterprise API token generated by a team admin from Feedly's Self Service page " +
    "(feedly.com/i/team/api → New API Token). Self-service tokens are only issued to Feedly for " +
    "Threat Intelligence (Enterprise) accounts — see sales@feedly.com if the page isn't visible " +
    "to you.",
  fields: [
    {
      key: "apiToken",
      label: "API Token",
      type: "secret",
      required: true,
      hint: "feedly.com/i/team/api → New API Token. Shown once at creation time only.",
    },
  ],

  /** The only hook handed the raw credential; network-less, stamps the header and returns. */
  sign({ request, credential }) {
    const cred = credential as Partial<FeedlyCredential>;
    for (const [name, value] of Object.entries(authHeaders(cred))) {
      request.headers[name] = value;
    }
    return request;
  },

  async test({ credential }, ctx) {
    const cred = credential as Partial<FeedlyCredential>;
    const token = (cred?.apiToken ?? "").trim();
    if (!token) return { ok: false, message: "credential missing apiToken" };

    const res = await ctx.fetch(`${API_BASE}${PROBE_PATH}`, {
      headers: { accept: "application/json", ...authHeaders({ apiToken: token }) },
    });
    if (res.ok) return { ok: true };

    const raw = await res.text().catch(() => "");
    let errorMessage: string | undefined;
    try {
      errorMessage = (JSON.parse(raw) as { errorMessage?: string }).errorMessage;
    } catch { /* not JSON */ }

    if (errorMessage === "must provide authorization token") {
      return {
        ok: false,
        message: "Feedly received no token. The credential did not reach the request — " +
          "reconnect this connection.",
      };
    }
    if (errorMessage === "invalid token" || res.status === 401) {
      return {
        ok: false,
        message: `Feedly rejected the token (401${errorMessage ? ` ${errorMessage}` : ""}). ` +
          "Check it was copied exactly and has not been revoked on feedly.com/i/team/api.",
      };
    }
    return { ok: false, message: formatFeedlyError(res.status, "GET", PROBE_PATH, raw) };
  },
};

export default bearerToken;
