import type { ActionDefinition } from "@w6w/types";
import { encodeId, TapfiliateClient } from "../lib/client.ts";
import { conversionIdParam } from "../lib/params.ts";

/** `GET /conversions/{conversion_id}/` */
interface Input {
  conversionId: number;
}

const conversionGet: ActionDefinition<Input> = {
  key: "conversion-get",
  type: "read",
  resource: "conversion",
  title: "Get Conversion",
  description: "Fetch a single conversion, including its commissions.",
  params: [conversionIdParam],
  output: [
    { key: "id", type: "number", label: "Conversion id" },
    { key: "external_id", type: "string", label: "Your own id for this conversion" },
    { key: "amount", type: "number", label: "Conversion amount" },
    { key: "commissions", type: "array", label: "Commissions generated by this conversion" },
    { key: "program", type: "object", label: "The program this conversion belongs to" },
    { key: "affiliate", type: "object", label: "The credited affiliate" },
    { key: "customer", type: "object", label: "The associated customer, if any" },
  ],

  async execute(input, ctx) {
    return await new TapfiliateClient(ctx).json(`/conversions/${encodeId(input.conversionId)}/`);
  },
};

export default conversionGet;
