import type { AuthDefinition } from "@w6w/types";
import { API_PATH, errorMessage, normalizeAccountDomain } from "../lib/client.ts";

/**
 * Long-Lived Token — a bearer token minted once, from inside the target
 * Kommo account.
 *
 * ## What Kommo actually offers, and why this one
 *
 * `developers.kommo.com/docs/kommo-for-developers` documents two ways in:
 * OAuth2 (an authorization-code / refresh-token dance against a registered
 * Integration, meant for a public Marketplace app one account owner installs
 * into another's account) and a Long-Lived Token, generated from
 * Settings -> API inside a **private integration** the account's own admin
 * creates. Kommo's own `long-lived-token` doc says it directly: "there's no
 * need to go through the difficult process of getting an authorization code
 * through the redirect mechanism [...] the integration will work with your
 * rights" — exactly the single-account, unattended case a workflow
 * Connection is. OAuth2 is declined here for the same reason Mautic's OAuth2
 * Authorization Code grant was: it needs a browser redirect and a live user
 * session to mint the first token, which an unattended workflow Connection
 * has neither of.
 *
 * The token carries the creating admin's own permissions, has NO refresh
 * token and NO refresh endpoint (there is nothing to renew — a new token is
 * generated by hand from the same Settings -> API screen once the old one's
 * chosen expiry, 1 day to 5 years, passes), and — per the doc's own warning —
 * is exactly as powerful as that admin's account access. Revoking it means
 * deleting the private integration in Kommo, same as rotating any other
 * long-lived secret.
 *
 * ## `type: "custom"`, not `"oauth2"`
 *
 * The `oauth2` type in this spec models the browser authorization-code flow
 * against a fixed `authorizationUrl`/`tokenUrl` pair. This grant has no
 * redirect step and no token endpoint to call at all — the token is copy-
 * pasted, already minted — so there is nothing for that config to describe.
 */

/** What this app persists on the Connection. */
export interface KommoCredential {
  accountDomain: string;
  token: string;
}

const longLivedToken: AuthDefinition = {
  key: "long-lived-token",
  type: "custom",
  displayName: "Long-Lived Token",
  description:
    "Create a private integration in your Kommo account (Settings -> API), open its Keys and " +
    "scopes tab, and click Generate long-lived token. Paste that token here along with your " +
    "account's address. The token carries the creating admin's own permissions and does not " +
    "refresh itself — generate a new one before the chosen expiry (1 day to 5 years) passes.",
  connectionLabel: "{{accountName}} @ {{accountDomain}}",
  fields: [
    {
      key: "accountDomain",
      label: "Account Address",
      type: "string",
      required: true,
      placeholder: "acme.kommo.com",
      hint: 'Your Kommo account\'s address. A bare name like "acme" is assumed to be ' +
        '"acme.kommo.com" — type the full "acme.amocrm.com" instead if your account predates ' +
        "the 2024 amoCRM → Kommo rebrand and was never moved.",
    },
    {
      key: "token",
      label: "Long-Lived Token",
      type: "secret",
      required: true,
      hint: "Settings → API → (your private integration) → Keys and scopes → " +
        "Generate long-lived token. Shown once — copy it immediately.",
    },
  ],

  /**
   * `exchange` normalises the pasted account address before it is stored, so
   * a URL pasted with a scheme or trailing path (Kommo's own docs show the
   * address bare, but a user will paste what is in their browser bar) does
   * not silently become part of every request path.
   */
  exchange({ fields }) {
    const f = (fields ?? {}) as Record<string, unknown>;
    const token = String(f.token ?? "").trim();
    if (!token) throw new Error("Long-Lived Token is required.");
    const accountDomain = normalizeAccountDomain(String(f.accountDomain ?? ""));
    return { accountDomain, token };
  },

  /**
   * `GET /api/v4/account` is the probe, chosen by reading its response body
   * rather than its name — the rule this pack learned from Follow Up Boss's
   * `/me` echoing the caller's own API key. Kommo's `account` response is id,
   * name, subdomain, country, currency and feature flags: no token, no
   * secret, nothing that traces back to the credential itself.
   *
   * It also needs no scope beyond existing, so a token minted with a narrow
   * private-integration scope set is never reported broken for lacking
   * access to some other resource.
   */
  async test({ credential }, ctx) {
    const cred = credential as Partial<KommoCredential>;
    if (!cred?.token) return { ok: false, message: "credential missing a token" };
    if (!cred?.accountDomain) return { ok: false, message: "credential missing accountDomain" };

    const res = await ctx.fetch(`https://${cred.accountDomain}${API_PATH}/account`, {
      headers: { accept: "application/json", authorization: `Bearer ${cred.token}` },
    });
    const text = await res.text().catch(() => "");
    if (res.status === 401) {
      return {
        ok: false,
        message: `Kommo rejected the token (401${
          errorMessage(text) ? `: ${errorMessage(text)}` : ""
        }). It may have expired or been revoked — generate a new one from Settings → API.`,
      };
    }
    if (res.status === 402) {
      return {
        ok: false,
        message: "Kommo returned 402 — this account's paid or trial period has ended.",
      };
    }
    if (res.status === 403) {
      return {
        ok: false,
        message: "Kommo returned 403 — the token authenticated, but lacks permission to " +
          "read the account.",
      };
    }
    if (res.status === 404) {
      return {
        ok: false,
        message: `no Kommo API at ${cred.accountDomain} (404) — check the account address.`,
      };
    }
    if (!res.ok) {
      return {
        ok: false,
        message: `Kommo returned ${res.status}${
          errorMessage(text) ? `: ${errorMessage(text)}` : ""
        }`,
      };
    }
    return { ok: true };
  },

  /**
   * Records the account's own name and id. Never the token.
   *
   * `afterConnect` only ever receives `{ credential }` — `exchange` has
   * already run by this point and normalised `accountDomain` onto it, so
   * there is no need to re-read the raw form `fields` here.
   */
  async afterConnect({ credential }, ctx) {
    const cred = credential as Partial<KommoCredential>;
    if (!cred?.accountDomain) return {};
    const accountDomain = cred.accountDomain;
    if (!cred?.token) return { accountDomain };

    try {
      const res = await ctx.fetch(`https://${accountDomain}${API_PATH}/account`, {
        headers: { accept: "application/json", authorization: `Bearer ${cred.token}` },
      });
      if (!res.ok) return { accountDomain };
      const body = await res.json().catch(() => null) as {
        id?: number;
        name?: string;
      } | null;
      if (!body) return { accountDomain };
      return { accountDomain, accountName: body.name, accountId: body.id };
    } catch {
      return { accountDomain };
    }
  },

  /** The only hook that stamps the token. Runs network-less. */
  sign({ request, credential }) {
    const { token } = credential as Partial<KommoCredential>;
    request.headers["authorization"] = `Bearer ${token ?? ""}`;
    return request;
  },
  // No `revoke`: Kommo's REST API documents no endpoint to invalidate a
  // Long-Lived Token. Deleting the private integration in Settings -> API
  // invalidates it, but that action is not exposed over the API this app can
  // reach — it is the operator's own step, same as rotating the token.
};

export default longLivedToken;
